replicaCount: 2

image:
  repository: 322814813226.dkr.ecr.us-east-1.amazonaws.com/hdfc-insurance
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

containerPort: 80
